---
title: "Mutation signature logos : Shiraishi et al 2015"
author: "Dongyue Xie"
date: YYYY-MM-DD
output: html_document
---


<!-- Add your analysis here -->
```{r,echo=FALSE,message=FALSE,fig.width=40,fig.height=28}
library(Logolas)
library(grid)
grid.newpage()
layout.rows <- 5
layout.cols <- 6
top.vp <- viewport(layout=grid.layout(layout.rows, layout.cols,
                                      widths=unit(rep(5,layout.cols), rep("null", 2)),
                                      heights=unit(rep(5,layout.rows), rep("null", 1))))
plot_reg <- vpList()
l <- 1
for(i in 1:layout.rows){
  for(j in 1:layout.cols){
    plot_reg[[l]] <- viewport(layout.pos.col = j, layout.pos.row = i, name = paste0("plotlogo", l))
    l <- l+1
  }
}


plot_tree <- vpTree(top.vp, plot_reg)

pushViewport(plot_tree)


for(i in c(1:27)){
 mat=read.table(paste('../data/Fig4_rawdata/sig_',i,'.txt',sep = ''))
  mat1=cbind(t(mat[2:3,1:4]),rep(NA,4),t(mat[4:5,1:4]))
  rownames(mat1)=c('A','C','G','T')
  colnames(mat1) = c("-2", "-1", "0", "1", "2")
  mat2=cbind(rep(NA,6),rep(NA,6),t(mat[1,]),rep(NA,6),rep(NA,6))
  colnames(mat2) = c("-2", "-1", "0", "1", "2")
  rownames(mat2) = c("C>A", "C>G", "C>T", "T>A", "T>C", "T>G")
  table = rbind(mat1, mat2)
  
  cols = RColorBrewer::brewer.pal.info[RColorBrewer::brewer.pal.info$category == 
'qual',]
col_vector = unlist(mapply(RColorBrewer::brewer.pal, cols$maxcolors, rownames(cols)))
total_chars = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O",
"P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "zero", "one", "two",
"three", "four", "five", "six", "seven", "eight", "nine", "dot", "comma",
"dash", "colon", "semicolon", "leftarrow", "rightarrow")

  set.seed(20)
color_profile <- list("type" = "per_symbol",
"col" = sample(col_vector, length(total_chars), replace=FALSE))
  
  # logomaker(table,
  #          color_profile = color_profile,
  #          frame_width = 1,
  #          xlab = "Position",
  #          ylab = "Information content",
  #          pop_name=paste('Logo plot',i))
seekViewport(paste0("plotlogo", i))
  nlogomaker(table,
             logoheight = 'ratio',
          color_profile = color_profile,
          frame_width = 1,
          xlab = "Position",
          
          pop_name = paste('Signature',i),
          newpage = F
          )
  
}
```
## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
