---
title: "Guided Tutorial"
output:
  html_document:
    toc: false
---

We present an elaborate guided tutorial of how to use the **Logolas** R package. 


- [Chapter 1:   Why Logolas?](intro.html)


- [Chapter 2:   Logo and EDLogo](FirstLook.html)


- [Chapter 3:   String Logos](extend.html)


- [Chapter 4:   Generating Consensus sequence from EDLogo](nomenclature.html)


- [Chapter 5:   Dirichlet Adaptive Shrinkage (dash)](dashtutor2.html)



For additional examples and analysis of logo visualizations, check out our Gallery and also [additional examples of Logolas visualizations](https://dongyuexie.github.io/Sequence-Motif-Depletion/) by Dongyue Xie.
 

The authors would like to acknowledge John Blischak, Po Yuan Tung, Chiaowen Joyce Hsiao, Hussein al Asadi, Alex White, Trevor Price, Peter Carbonetto and Yuichi Shiraishi for helpful discussions and contribution to the project. 


----------------------------------------------------------------------------

**Thank you for using Logolas !**  

If you have any questions, you can either open an issue in our [Github page](https://github.com/kkdey/Logolas) or write to Kushal K Dey (kkdey@uchicago.edu). Also please feel free to contribute to the package. You can contribute by submitting a pull request or by communicating with the said person.









